### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by tr1ms** [mumbo-pro/portal-front#8]
Upon starting the application with `npm start` the app break with the following error:
```html
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:1039:7)
    at noopServiceWorkerMiddleware (/mnt/c/Users/gsonl/Workspace/portal-front/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/mnt/c/Users/gsonl/Workspace/portal-front/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/mnt/c/Users/gsonl/Workspace/portal-front/node_modules/express/lib/router/index.js:317:13)
    at /mnt/c/Users/gsonl/Workspace/portal-front/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/mnt/c/Users/gsonl/Workspace/portal-front/node_modules/express/lib/router/index.js:335:12)
    at next (/mnt/c/Users/gsonl/Workspace/portal-front/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/mnt/c/Users/gsonl/Workspace/portal-front/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/mnt/c/Users/gsonl/Workspace/portal-front/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/mnt/c/Users/gsonl/Workspace/portal-front/node_modules/express/lib/router/index.js:317:13)
    at /mnt/c/Users/gsonl/Workspace/portal-front/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/mnt/c/Users/gsonl/Workspace/portal-front/node_modules/express/lib/router/index.js:335:12)
    at next (/mnt/c/Users/gsonl/Workspace/portal-front/node_modules/express/lib/router/index.js:275:10)
    at handleWebpackInternalMiddleware (/mnt/c/Users/gsonl/Workspace/portal-front/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (/mnt/c/Users/gsonl/Workspace/portal-front/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by tr1ms** [comment]
Upgrading the `react-scripts` to `^3.4.1` and clearing npm cache seems to fix the current issue and the app starts fine. I can submit a PR with updated package version. 

But then my machine fails to connect to the foreign host saying connection refused, more details here [ECONNREFUSED](https://nodejs.org/api/errors.html#errors_common_system_errors). Is there anyhow to go around this?

**Comment by alphaolomi** [comment]
> Upgrading the `react-scripts` to `^3.4.1` and clearing npm cache seems to fix the current issue and the app starts fine. I can submit a PR with updated package version.
> 
> But then my machine fails to connect to the foreign host saying connection refused, more details here [ECONNREFUSED](https://nodejs.org/api/errors.html#errors_common_system_errors). Is there anyhow to go around this?

yes a fix would be nice @gsonly
